export const SEND_MESSAGE = 'SEND_MESSAGE'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const SELECT_USER1 = 'SELECT_USER1'
export const SELECT_USER2 = 'SELECT_USER2'
export const EDIT_TEXT = 'EDIT_TEXT'
